ngo_finder/ngo_finder/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'directory.views.main', name='home'),
    url(r'^login/', 'auth.views.login_user'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    #url(r'^ngolist', 'directory.views.ngolist'),
    url(r'^ngo/(\d+)', 'directory.views.ngo'),
    url(r'^contact/', 'directory.views.contact'),
    url(r'^about/', 'directory.views.about'),

    # search routes
    (r'^search/', include('haystack.urls')),
)

ngo_finder/directory/models.py
from django.db import models
from django.contrib.auth.models import User

class Geo_scope(models.Model):
    scope = models.CharField(max_length=255)
    
    def __unicode__(self):
        return self.scope

class Sector(models.Model):
    sector = models.CharField(max_length=255)

    def __unicode__(self):
        return self.sector

class Organization(models.Model):
    name = models.CharField(max_length=255)
    geo_scope = models.ForeignKey(Geo_scope,null=True)
    sectors = models.ManyToManyField(Sector)
    url = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name

class Location(models.Model):
    organization = models.ForeignKey(Organization)
    primary = models.BooleanField(default=False) # record is org's main location
    url = models.CharField(max_length=255)
    country = models.CharField(max_length=255,null=True)
    state = models.CharField(max_length=255,null=True)
    county = models.CharField(max_length=255,null=True)
    city = models.CharField(max_length=255,null=True)
    street = models.CharField(max_length=255,null=True)
    postalcode = models.CharField(max_length=255,null=True)

    def __unicode__(self):
        if self.city:
            return ','.join(self.country,self.state,self.county,self.city)
        else:
            return ','.join(self.country,self.state,self.county)

class Operation(models.Model):
    organization = models.ForeignKey(Organization)
    countries = models.TextField(null=True)
    states = models.TextField(null=True)
    counties = models.TextField(null=True)
    cities = models.TextField(null=True)

    def __unicode__(self):
        return 'Op #'+self.pk

class Contact(models.Model):
    organization = models.ForeignKey(Organization)
    name = models.CharField(max_length=255,null=True)
    email = models.EmailField(max_length=255,null=True)
    primary_phone = models.CharField(max_length=255,null=True)
    secondary_phone = models.CharField(max_length=255,null=True)
    
    def __unicode__(self):
        return self.name

class Comment(models.Model):
    organization = models.ForeignKey(Organization)
    user = models.ForeignKey(User)
    subject = models.CharField(max_length=255,null=True)
    text = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

ngo_finder/directory/views.py
from django.http import HttpResponse
from django.shortcuts import render_to_response
from directory.models import Organization, Comment
from django.core.context_processors import csrf
from django.template import RequestContext

def main(request):
    c = RequestContext(request,{})
    c.update(csrf(request))
    return render_to_response("directory/main.html",c)

def ngo(request, ngo_id):
    organization = Organization.objects.filter(id = ngo_id).get()    
    if request.POST:
        comment_text = request.POST.get('comment')
        comment = Comment()
        comment.organization = organization
        comment.user = request.user
        comment.subject = request.POST.get('subject')
        comment.text = comment_text
        comment.save()
    c = RequestContext(request,{"organization" : organization})
    c.update(csrf(request))
    return render_to_response("directory/profile.html", c)
    
def about(request):
    c = RequestContext(request,{})
    c.update(csrf(request))
    return render_to_response("directory/about.html",c)

def contact(request):
    c = RequestContext(request,{})
    c.update(csrf(request))
    return render_to_response("directory/contact.html",c)

ngo_finder/directory/templates/directory/about.html
{% extends "directory/base.html" %}
{% block content %}
<h3>About</h3>
<p>
NGO Finder is a project first developed at Random Hacks of Kindess in December 2012. It is a platform to enable Peace Corps volunteers to update information about non-governmental organizations in areas that are served by the corps.  Currently, this app is in development, and the data is limited to NGO's in Zambia. If you would like to contribute to this effort, please reach out via the <a href="/contact/">contact</a> page!
</p>
{% endblock %}

ngo_finder/directory/templates/directory/base-new.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Bootstrap, from Twitter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Project name</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <h1>Bootstrap starter template</h1>
      <p>Use this document as a way to quick start any new project.<br> All you get is this message and a barebones HTML document.</p>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../assets/js/jquery.js"></script>
    <script src="../assets/js/bootstrap-transition.js"></script>
    <script src="../assets/js/bootstrap-alert.js"></script>
    <script src="../assets/js/bootstrap-modal.js"></script>
    <script src="../assets/js/bootstrap-dropdown.js"></script>
    <script src="../assets/js/bootstrap-scrollspy.js"></script>
    <script src="../assets/js/bootstrap-tab.js"></script>
    <script src="../assets/js/bootstrap-tooltip.js"></script>
    <script src="../assets/js/bootstrap-popover.js"></script>
    <script src="../assets/js/bootstrap-button.js"></script>
    <script src="../assets/js/bootstrap-collapse.js"></script>
    <script src="../assets/js/bootstrap-carousel.js"></script>
    <script src="../assets/js/bootstrap-typeahead.js"></script>

  </body>
</html>

ngo_finder/directory/templates/directory/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>NGO-Finder</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/style.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
      
      li {
        list-style-type: none;
        }
    </style>
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/">NGO Finder</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="/">Home</a></li>
              <li><a href="/about/">About</a></li>
              <li><a href="/contact/">Contact</a></li>
            </ul>
            <p class="navbar-text pull-right">        
    {% if user.is_authenticated %}
                Hello {{ user.first_name }}!
	{% else %}
        	    <a href="/login/">Log In</a>
	{% endif %}
	        </p>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
    
    	  {% block content %}{% endblock %}

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{ STATIC_URL }}js/jquery.js"></script>

  </body>
</html>

ngo_finder/directory/templates/directory/contact.html
{% extends "directory/base.html" %}
{% block content %}
<h3 class="span12">Contact</h3>
<div class="row">
  <dl class="itemList">
    <dt class="span2" style="padding-left:2em">name:</dt>          <dd class="span10">Sarah Blazucki, Project Manager</dd>
    <dt class="span2" style="padding-left:2em">email:</dt>         <dd class="span10">sblazucki@peacecorps.gov</dd>
  </dl>
</div>
<div class="row">
  <dl class="itemList">
    <dt class="span2" style="padding-left:2em">name:</dt>          <dd class="span10">Development and Support</dd>
    <dt class="span2" style="padding-left:2em">email:</dt>         <dd class="span10">ngofinder@googlegroups.com</dd>
  </dl>
</div>
{% endblock %}

ngo_finder/directory/templates/directory/hello_world.html
{% extends "directory/base.html" %}
{% block content %}
  <a href="search">Search</a>
{% endblock %}

ngo_finder/directory/templates/directory/main.html
{% extends "directory/base.html" %}
{% block content %}
<div id="left">
      <h1>Welcome to NGO Finder</h1>
      <p>Click the link below to get started!</p>
</div>
<div id="right">
  <a href="search">Search</a>
</div>
{% endblock %}

ngo_finder/directory/templates/directory/profile.html
{% extends 'directory/base.html' %}
{% block content %}

<h1>{{ organization.name }}</h1>

<h3 class="span12">Location(s)</h3>
{% for location in organization.location_set.all %}
    <dl class="itemList">
      <dt class="span2">country:</dt>       <dd class="span10">{{ location.country|default_if_none:"n/a"   }}</dd>
      <dt class="span2">state:</dt>         <dd class="span10">{{ location.state|default_if_none:"n/a"     }}</dd>
      <dt class="span2">county:</dt>        <dd class="span10">{{ location.county|default_if_none:"n/a"    }}</dd>
      <dt class="span2">city:</dt>          <dd class="span10">{{ location.city|default_if_none:"n/a"      }}</dd>
      <dt class="span2">street:</dt>        <dd class="span10">{{ location.street|default_if_none:"n/a"    }}</dd>
      <dt class="span2">postalcode:</dt>    <dd class="span10">{{ location.postalcode|default_if_none:"n/a"}}</dd>
    </dl>
  {% endfor %}
  <h3 class="span12">Sectors:</h3>
  <dl>
    {% for sector in organization.sector_set.all %}
    <dt class="span2">Sector:</dt>    <dd class="span10">{{ sector.sector }}</dd>
    {% endfor %}
  </dl>

<h3 class="span12">Contact(s)</h3>
{% for contact in organization.contact_set.all %}
  <dl class="itemList">
    <dt class="span2">name:</dt>          <dd class="span10">{{ contact.name|default_if_none:"n/a"             }}</dd>
    <dt class="span2">email:</dt>         <dd class="span10">{{ contact.email|default_if_none:"n/a"            }}</dd>
    <dt class="span2">primary:</dt>       <dd class="span10">{{ contact.primary_phone|default_if_none:"n/a"    }}</dd>
    <dt class="span2">secondary:</dt>     <dd class="span10">{{ contact.secondary_phone|default_if_none:"n/a"  }}</dd>
  </dl>
{% endfor %}
{% if user.is_staff %}
<h3 class="span12">Note(s)</h3>
{% for comment in organization.comment_set.all %}
<span style='font-weight:bold'>Note:</span>
<div class="comment">
<span style="font-weight:bold">First Name:</span>{{ comment.user.first_name }}<br />
<span style="font-weight:bold">Last Name:</span>{{ comment.user.last_name }}<br />
<span style="font-weight:bold">subject:</span>{{ comment.subject }}<br />
<span style="font-weight:bold">text:</span>{{ comment.text }}<br />
<span style="font-weight:bold">created:</span>{{ comment.created_at }}<br />
<span style="font-weight:bold">updated:</span>{{ comment.updated_at }}<br />
</div>
<br />

{% endfor %}
<h3>Add a Note</h3>
<div>
  <form action="" method="post" />
{% csrf_token %}
    <label for="subject" style="font-weight:bold">Subject:</label>
    <input type="text" name="subject" /><br />
    <label for="comment" style="font-weight:bold">Notes:</label><br />
    <textarea rows="10" cols="50" name="comment"></textarea><br />
    <input type='submit' name='submit' value="Submit Comment"/>
  </form>
</div>
{% endif %}
{% endblock %}

ngo_finder/directory/templates/search/search.html
{% extends "directory/base.html" %}

{% block content %}
   <h2>Search</h2>

    <form method="get" action=".">
        <table>
            {{ form.as_table }}
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Search">
                </td>
            </tr>
        </table>

        {% if query %}
            <h3>Results</h3>

            {% for result in page.object_list %}
                <p>
                    <a href="/ngo/{{ result.object.id }}">{{ result.object.name }}</a>
                </p>
            {% empty %}
                <p>No results found.</p>
            {% endfor %}

            {% if page.has_previous or page.has_next %}
                <div>
                    {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
                    |
                    {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
                </div>
            {% endif %}
        {% else %}
            {# Show some example queries to run, maybe query syntax, something else? #}
        {% endif %}
    </form>
{% endblock %}